# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcache', '0002_checklist_checklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
