# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-04 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcache', '0004_auto_20161130_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
