# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcache', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='cloudcache.Category'),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cloudcache.Category'),
        ),
    ]
