# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcache', '0007_auto_20170420_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='cloudcache.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cloudcache.Category'),
            preserve_default=False,
        ),
    ]
